### ISSUE TITLE
Move Codefresh deploy pipeline to Github Actions

### ISSUE THREAD

**Issue by mvorisek** [atk4/infrastructure#13]
@romaninsh: This is to address memory issue, public visibility of a pipeline errors and also integrate with the terraforming

**Comment by romaninsh** [comment]
Some comments:

> @ATK Contributors It looks like the new release has a changed UI demo setup which does not work installed in a subdirectory to the WWW server anymore :slight_smile: I would have to move it to webroot/demos that the links work fine. Is that intentional or am I doing something wrong now?

> Also on ui.agiletookit.org the Viw Source links to GitHub don't point correctly to the sub-directories anymore

**Comment by mvorisek** [comment]
@ibelar related probably with https://github.com/atk4/ui/pull/1122

**Comment by ibelar** [comment]
The link there, in init.php, will need to point out to the proper branch instead of develop for older release. Like: https://github.com/atk4/ui/blob/2.0.0/demos/
Where should it be changed?  in latest tags release branch?

https://github.com/atk4/ui/blob/3fdbd86cca258f48295eb819cb250ab58110cc72/demos/init.php#L192

**Comment by romaninsh** [comment]
i've fixed memory issue in codefresh, in the future could migrate to our own runners, for now it should be fine.
